package com.tang.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTeacherTaskbook<M extends BaseTeacherTaskbook<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("isDelete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("isDelete");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setTeacherId(java.lang.String teacherId) {
		set("teacherId", teacherId);
	}

	public java.lang.String getTeacherId() {
		return get("teacherId");
	}

	public void setTaskbookId(java.lang.String taskbookId) {
		set("taskbookId", taskbookId);
	}

	public java.lang.String getTaskbookId() {
		return get("taskbookId");
	}

}
