package com.tang.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCollege<M extends BaseCollege<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("isDelete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("isDelete");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setCollegeName(java.lang.String collegeName) {
		set("collegeName", collegeName);
	}

	public java.lang.String getCollegeName() {
		return get("collegeName");
	}

	public void setCollegeDes(java.lang.String collegeDes) {
		set("collegeDes", collegeDes);
	}

	public java.lang.String getCollegeDes() {
		return get("collegeDes");
	}

	public void setSchoolId(java.lang.String schoolId) {
		set("schoolId", schoolId);
	}

	public java.lang.String getSchoolId() {
		return get("schoolId");
	}

}
