package com.tang.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDictionary<M extends BaseDictionary<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setIsDelete(java.lang.Integer isDelete) {
		set("isDelete", isDelete);
	}

	public java.lang.Integer getIsDelete() {
		return get("isDelete");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setField(java.lang.String field) {
		set("field", field);
	}

	public java.lang.String getField() {
		return get("field");
	}

	public void setValue(java.lang.Integer value) {
		set("value", value);
	}

	public java.lang.Integer getValue() {
		return get("value");
	}

	public void setMean(java.lang.String mean) {
		set("mean", mean);
	}

	public java.lang.String getMean() {
		return get("mean");
	}

}
