package com.tang.model;

import com.tang.model.base.BaseClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Class extends BaseClass<Class> {
	public static final Class dao = new Class();
}
