package com.tang.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import com.tang.bean.RequestBean;
import com.tang.model.base.BaseClass;
import com.tang.util.ParamKit;
import com.tang.util.SysConstant;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Class extends BaseClass<Class> {
	public static final Class dao = new Class();

	/**
	 * 获取学院下的所有班级
	 * @param requestBean
	 * @return
	 */
	public List<Record> queryClass(RequestBean requestBean){
		String schoolId = ParamKit.checkObjectNotNull(requestBean,"schoolId");
		String collegeId = ParamKit.checkObjectNotNull(requestBean,"collegeId");
		return Db.find("SELECT * FROM class WHERE schooolId = ? AND collegeId = ? AND isDelete = ?",schoolId,collegeId, SysConstant.ISDELETE.NO);
	}

}
