package com.tang.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import com.tang.bean.RequestBean;
import com.tang.model.base.BaseMajor;
import com.tang.util.ParamKit;
import com.tang.util.SysConstant;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Major extends BaseMajor<Major> {
	public static final Major dao = new Major();

	/**
	 * 获取学院下的所有专业
	 * @param requestBean
	 * @return
	 */
	public List<Record> queryMajor(RequestBean requestBean){
		String schoolId = ParamKit.checkObjectNotNull(requestBean, "schoolId");
		String collegeId = ParamKit.checkObjectNotNull(requestBean,"collegeId");
		return Db.find("SELECT * FROM major WHERE schooolId = ? AND collegeId = ? AND isDelete = ?", schoolId, collegeId, SysConstant.ISDELETE.NO);
	}
}
