package com.tang.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import com.tang.model.base.BaseSchool;
import com.tang.util.SysConstant;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class School extends BaseSchool<School> {
	public static final School dao = new School();

	public List<Record> querySchoolInfo(){
		return Db.find("SELECT * FROM school WHERE isDelete = ?", SysConstant.ISDELETE.NO);
	}
}
