package com.tang.model;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;
import com.tang.model.base.BaseTeacher;
import com.tang.util.DateUtils;
import com.tang.util.IDKit;
import com.tang.util.SysConstant;
import java.util.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Teacher extends BaseTeacher<Teacher> {
	public static final Teacher dao = new Teacher();

	/**
	 * 填写教师信息（完善个人信息）
	 * @param userId
	 * @param schoolId
	 * @param collegeId
	 * @param classId
	 * @param bornDate
	 * @param sex
	 * @param name
	 * @return
	 */
	public Boolean saveTeacherInfo(String userId,String schoolId,String collegeId,String classId,Date bornDate,int sex,String name){
		Record teacher = new Record();
		teacher.set("id", IDKit.uuid())
				.set("isDelete", SysConstant.ISDELETE.NO)
				.set("createTime", DateUtils.getCurrentDate())
				.set("updateTime",DateUtils.getCurrentDate())
				.set("teachername",name)
				.set("sex",sex)
				.set("bornDate",bornDate)
				.set("classId",classId)
				.set("collegeId",collegeId)
				.set("schoolId",schoolId)
				.set("userId", userId);
		Boolean result = Db.save("teacher", teacher);
		return result;
	}
}
