package com.tang.model;

import com.tang.model.base.BaseTeacherTaskbook;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TeacherTaskbook extends BaseTeacherTaskbook<TeacherTaskbook> {
	public static final TeacherTaskbook dao = new TeacherTaskbook();
}
