package com.tang.model;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;
import com.tang.bean.RequestBean;
import com.tang.model.base.BaseUser;
import com.tang.util.IDKit;
import com.tang.util.ParamKit;
import com.tang.util.SysConstant;
import org.apache.xmlbeans.impl.tool.Extension;

import java.util.Date;

/**
 * Generated by JFinal.
 * User model.
 * 数据库字段名建议使用驼峰命名规则，便于与 java 代码保持一致，如字段名： userId
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	
	public static final User me = new User();
	/**
	 * 所有 sql 与业务逻辑写在 Model 或 Service 中，不要写在 Controller 中，养成好习惯，有利于大型项目的开发与维护
	 */
	public Page<User> paginate(int pageNumber, int pageSize) {
		return paginate(pageNumber, pageSize, "select *", "from user order by id asc");
	}

	public Record userRegister(RequestBean requestBean){
		String userName = ParamKit.checkObjectNotNull(requestBean,"username");
		String userPwd = ParamKit.checkObjectNotNull(requestBean,"password");
		String userRole = ParamKit.checkObjectNotNull(requestBean,"userRole");
		Record record = new Record();
		record.set("id", IDKit.uuid())
				.set("userName",userName)
				.set("password",userPwd)
				.set("userRole",userRole)
				.set("isDelete", SysConstant.ISDELETE.NO)
				.set("createTime",new Date())
				.set("updateTime", new Date());
		Db.save("user",record);
		return record;
	}

	public Record userLogin(RequestBean requestBean){
		String username = ParamKit.checkObjectNotNull(requestBean,"username");
		String password = ParamKit.checkObjectNotNull(requestBean,"password");
        String sql = "SELECT * FROM user WHERE userName = ? AND password = ? AND isDelete = ?";
		Record record = Db.findFirst(sql, username, password, SysConstant.ISDELETE.NO);
		return  record;
	}
}


